# tasks file
---
- name: repository | install dependencies (pre)
  ansible.builtin.apt:
    name: "{{ percona_toolkit_dependencies_pre }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - percona-toolkit-repository-install-dependencies

- name: repository | (keyrings) directory | create
  ansible.builtin.file:
    path: "{{ percona_toolkit_keyring_dst | dirname }}"
    state: directory
    owner: root
    group: root
    mode: '0755'
  tags:
    - percona-toolkit-repository-keyrings-directory-create

- name: repository | (keyring) file | download
  ansible.builtin.apt_key:
    id: "{{ percona_toolkit_keyring_id }}"
    keyserver: "{{ apt_key_keyserver | default('keyserver.ubuntu.com') }}"
    keyring: "{{ percona_toolkit_keyring_dst }}"
    state: present
  tags:
    - percona-toolkit-repository-keyring-file-download

- name: repository | add
  ansible.builtin.apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: "{{ item.state | default('present') }}"
    update_cache: true
    mode: '0644'
  with_items: "{{ percona_toolkit_repositories }}"
  tags:
    - percona-toolkit-repository-add

- name: repository | apt-pin packages
  ansible.builtin.copy:
    src: etc/apt/preferences.d/00percona.pref
    dest: /etc/apt/preferences.d/00percona.pref
    owner: root
    group: root
    mode: '0644'
  tags:
    - percona-toolkit-repository-apt-pin
