# tasks file
---
- name: repository | install | dependencies (pre)
  ansible.builtin.apt:
    name: "{{ percona_toolkit_dependencies_pre }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - percona-toolkit-repository-install
    - percona-toolkit-repository-install-dependencies

- name: repository | add public key
  ansible.builtin.apt_key:
    id: 9334A25F8507EFA5
    keyserver: keyserver.ubuntu.com
    state: present
  tags:
    - percona-toolkit-repository-public-key

- name: repository | add
  ansible.builtin.apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: true
  with_items: "{{ percona_toolkit_repositories }}"
  tags:
    - percona-toolkit-repository-add

- name: repository | apt-pin packages
  ansible.builtin.copy:
    src: etc/apt/preferences.d/00percona.pref
    dest: /etc/apt/preferences.d/00percona.pref
    owner: root
    group: root
    mode: 0644
  tags:
    - percona-toolkit-repository-apt-pin
